import Navbar from '@/components/nav'
import '@/styles/globals.css'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/footer.module.css'


export default function App({ Component, pageProps }) {
  return <>
   <Head>
        <title>OmegaMC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Omega.ico" />
      </Head>
      <header>
        <Link href='/'>
         Omega MC
        </Link>
           <Navbar />
        </header>
  <Component {...pageProps} />
        <footer>
          <Link href='/about'>Sobre nosotros</Link>
          <div className={styles.whats}>
            <img src='/whats.ico' className={styles.icon}/>
            <h3>56 32 89 02 91</h3>
          </div>
        </footer> 
  </>
}
