import '@/styles/globals.css'
import Head from 'next/head'
import Link from 'next/link'

export default function App({ Component, pageProps }) {
  return <>
   <Head>
        <title>OmegaMC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Omega.ico" />
      </Head>
      <header>
        <Link href='/'>
         Omega MC
        </Link>
        </header>
  <Component {...pageProps} />
  </>
}
