import '@/styles/globals.css'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {FaTools} from 'react-icons/fa'
import {BiFridge} from 'react-icons/bi'
import {MdPointOfSale} from 'react-icons/md'
import {GiWashingMachine,GiThermometerCold,GiBlender,GiPuzzle} from 'react-icons/gi'

export default function App({ Component, pageProps }) {
  return <>
   <Head>
        <title>OmegaMC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Omega.ico" />
      </Head>
      <header>
        <Link href='/'>
         Omega MC
        </Link>
        <div className={styles.maves}>
        <Link href='/about'  className={styles.links}>
      Sobre Nosotros
      </Link>
      <img src='/Omega.ico' className={styles.ico}/>
     <Link href='/services' className={styles.links}>
      Servicios <FaTools />
     </Link> 
     <Link href='/refrigeracion' className={styles.links}>Refrigeracion<BiFridge/></Link>
     <Link href='/lavado' className={styles.links}>Lavado<GiWashingMachine/></Link>
     <Link href='/aire/aire' className={styles.links}>Air Acon<GiThermometerCold/></Link>
     <Link href='/electrodomesticos/electrodomesticos' className={styles.links}>Varios<GiBlender/></Link>
     <Link href='/refac' className={styles.links}>Refacciones<GiPuzzle/></Link>
     <Link href='/venta' className={styles.links}>Venta<MdPointOfSale/></Link>
        </div>
        </header>
  <Component {...pageProps} />
        <footer>
          <Link href='/about'>Sobre nosotros</Link>
        </footer> 
  </>
}
